### ISSUE TITLE
Tutorial is not copy-paste able

### ISSUE THREAD

**Issue by philip30** [neubig/lamtram#15]
In the README section:

$ export LD_LIBARY_PATH="$DYNET_DIR/build/dynet:$LD_LIBRARY_PATH"

I think it should be "LD_LIBRARY_PATH"

**Comment by neubig** [comment]
Sure, if you notice something small like this could you send

**Comment by neubig** [comment]
Fixed by https://github.com/neubig/lamtram/commit/dde6ac39aaf5ac88391c9805aa1347d6c2fc2875
If you find little things like this a pull-request would be appreciated!
