### ISSUE TITLE
How to appropriately link cuda-compiled dynet with Lamtram?

### ISSUE THREAD

**Issue by philip30** [neubig/lamtram#16]
As far as I see, this is mentioned in the dynet tutorial page.
I am not sure though, I tried to follow the instruction there but still failed.

I think it is a good idea to have a page tutorial about using GPU (or, is it already available?)

**Comment by neubig** [comment]
Should be fixed by https://github.com/neubig/lamtram/commit/71a5871289214231998b9d968adf123df9968d61
