### ISSUE TITLE
Error making lantram

### ISSUE THREAD

**Issue by naserrazavi** [neubig/lamtram#21]
razavi@razavi-G20AJ:~/dynet-base/lamtram$ make
Making all in src
make[1]: Entering directory '/home/razavi/dynet-base/lamtram/src'
Making all in lamtram
make[2]: Entering directory '/home/razavi/dynet-base/lamtram/src/lamtram'
make  all-am
make[3]: Entering directory '/home/razavi/dynet-base/lamtram/src/lamtram'
depbase=`echo lamtram-train.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.    -I/usr/include -I~/dynet-base/eigen -I~/dynet-base/dynet -I~/usr/local/cuda/include -DHAVE_CUDA -DEIGEN_USE_GPU -DEIGEN_HAS_CUDA_FP16 -fopenmp -I./.. -g -O2 -std=c++0x -MT lamtram-train.lo -MD -MP -MF $depbase.Tpo -c -o lamtram-train.lo lamtram-train.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/usr/include "-I~/dynet-base/eigen" "-I~/dynet-base/dynet" "-I~/usr/local/cuda/include" -DHAVE_CUDA -DEIGEN_USE_GPU -DEIGEN_HAS_CUDA_FP16 -fopenmp -I./.. -g -O2 -std=c++0x -MT lamtram-train.lo -MD -MP -MF .deps/lamtram-train.Tpo -c lamtram-train.cc  -fPIC -DPIC -o .libs/lamtram-train.o
In file included from lamtram-train.cc:2:0:
./../lamtram/lamtram-train.h:4:26: fatal error: dynet/tensor.h: No such file or directory
compilation terminated.
Makefile:657: recipe for target 'lamtram-train.lo' failed
make[3]: *** [lamtram-train.lo] Error 1
make[3]: Leaving directory '/home/razavi/dynet-base/lamtram/src/lamtram'
Makefile:443: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/razavi/dynet-base/lamtram/src/lamtram'
Makefile:369: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/razavi/dynet-base/lamtram/src'
Makefile:400: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by neubig** [comment]
It looks like you are specifying the relative path to DyNet using the `~` symbol. Could you try specifying the absolute path?

**Comment by naserrazavi** [comment]
many thanks, I tried to use absolute path but this time I got the following error:

/home/razavi/dynet-base/dynet/dynet/cuda.h:9:18: fatal error: cuda.h: No such file or directory

**Comment by neubig** [comment]
Does the `/home/razavi/dynet-base/dynet/dynet/cuda.h` file exist? Perhaps you need to set `--with-dynet=/home/razavi/dynet-base`?

**Comment by naserrazavi** [comment]
Sorry It was my fault and the problem is solved using absolute path. Many many thanks.
It is a very interesting library to use. Many thanks again.

**Comment by neubig** [comment]
No problem! Glad the problem was resolved.
