### ISSUE TITLE
codes about annotations 

### ISSUE THREAD

**Issue by liesun1994** [neubig/lamtram#23]
I feel puzzled when reading lamtram code , so is there any detailed annotations when lamtram will be updated next time?

**Comment by neubig** [comment]
I understand your puzzlement. As lamtram developed very organically with
the progress of neural machine translation, there were some design
decisions that don't make sense given what modern architectures look like.
We're in the progress of creating a major overhaul that may be done
sometime soon, which should be significantly easier to understand. I'll
announce it here when we're done.

**Comment by liesun1994** [comment]
thx. it's a nice framework. hope it be a widely spread frameword. and of course be easy to understand. Aha

**Comment by neubig** [comment]
We've made public `xnmt`, a translation framework based on DyNet that is meant to replace lamtram at some point:
https://github.com/neulab/xnmt/

There are still a number of features in lamtram that aren't implemented in xnmt yet, but we're planning on getting most of them implemented soon. If you're interested, take a look!
