### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by mehmedes** [neubig/lamtram#3]
Good morning Graham,

Actually, I don't have an issue to report. I just wanted to say thank you for your research und providing this system. 

I've followed your instructions in nmt tips and I'm currently setting up an English-German NMT system based on Europarl and News Commentary. I'm using a Google VM with 8 vCPUs, 52 GB Ram and 1TB hard disk.  I started the training process yesterday at ppl ~1700. I'm still at epoch 1 and the ppl has dropped to ~360.

This is the command I used after pre-processing the corpus:

lamtram/src/lamtram/lamtram-train --cnn-mem 30000 --model_type encatt --train_src /home/mehmedes777/data/train.unk.en --train_trg /home/mehmedes777/data/train.unk.de --dev_src /home/mehmedes777/data/dev.en --dev_trg /home/mehmedes777/data/dev.de --attention_lex prior:file=/home/mehmedes777/lexicon/train.ende.prob:alpha=0.0001 --layers lstm:200:1 --trainer adam --learning_rate 0.001 --minibatch_size 256 --rate_decay 1.0 --epochs 10 --motdel_out models/encatt-unk-stop-lex-w200.mod

I'm looking forward to the outcome!

**Comment by neubig** [comment]
Thank you for the positive feedback!
