### ISSUE TITLE
Source Text for Translation 

### ISSUE THREAD

**Issue by mehmedes** [neubig/lamtram#6]
Please excuse my question but where do I enter the source text for translation:

Decoding

You can also generate the most likely translation for the input sentence. Here is a typical use case.

src/lamtram/lamtram \
    --operation gen \
    --models_in encdec=transmodel.out \
    --beam 5 \        # Perform beam search with a beam of 5
    --word_pen 0.0 \  # The word penalty can be used to increase or decrease
                      # the average length of the sentence (positive for more words)
    > results.txt

Should I use src_in ...?

**Comment by neubig** [comment]
Yes! Thanks for catching the silly oversight, this has been fixed.
