### ISSUE TITLE
Using dynet's master branch instead of v2?

### ISSUE THREAD

**Issue by yuchenz** [neubig/lamtram#7]
Hi Graham,

I like lamtram! Thanks for building this toolkit! I was using it before cnn is updated to dynet, but now I have a question: the readme says that I should use v2 branch of dynet, however, it seems that dynet doesn't have a v2 branch anymore. Am I supposed to use the master branch of it? Thank you!

Best,
Yuchen

**Comment by pmichel31415** [comment]
Hi Yuchen, 

Dynet was recently updated from the v2 of cnn so this information might be out of date. It should work with the master branch of Dynet, Graham correct me if I'm wrong.

Cheers

**Comment by neubig** [comment]
That's correct! I fixed the README to remove the reference to v2.

**Comment by yuchenz** [comment]
Hi pmichel31415 and Graham,

Thanks! I used the following steps to compile lamtram before, but it doesn't work anymore now. Could you help me check what went wrong here? The steps are:

in one directory I compiled dynet:
```
$ git clone https://github.com/clab/dynet.git
$ cd dynet
$ mkdir build
$ cd build
$ cmake .. -DEIGEN3_INCLUDE_DIR=/my/path/to/eigen
$ make -j 2
```
and dynet test `./examples/xor` works fine.

in another directory I compiled lamtram:
```
$ git clone https://github.com/neubig/lamtram.git
$ autoreconf -i
$ ./configure --with-dynet=/my/path/to/dynet --with-eigen=/my/path/to/eigen
$ make
```

then with my data, I tried to train a translation model:
```
$ ~/tools/lamtram_w_dynet/lamtram/src/lamtram/lamtram-train --model_type encdec --context 2 --layers "lstm:100:1" --trainer sgd --learning_rate 0.1 --seed 0 \
> --train_src fbis_10.ch.unk --train_trg fbis_10.en.unk --dev_src mt06_10.ch --dev_trg mt06_10.en --model_out toy_model.out 
```
but got this error:
```
~/tools/lamtram_w_dynet/lamtram/src/lamtram/.libs/lt-lamtram-train: error while loading shared libraries: libdynet.so: cannot open shared object file: No such file or directory
```

Thank you very much!

**Comment by yuchenz** [comment]
and I checked libdynet.so is in /my/path/to/dynet/build/dynet/

**Comment by neubig** [comment]
Sorry, you'll need to add "/my/path/to/dynet/build/dynet/" to your
LD_LIBRARY_PATH. I'll update the README in a bit.

Graham

**Comment by yuchenz** [comment]
Oh I see! Yup it's working now. Thank you very much!!

Best,
Yuchen

**Comment by mehmedes** [comment]
When I try to compile lamtram and usemake, I get the following error:

/bin/bash ../../libtool  --tag=CXX   --mode=link g++ -I/usr/include -I/home/???/eigen -I/home/???/dynet -fopenmp -I./.. -g -O2 -std=c++0x   -o lamtram-train lamtram-train-main.o liblamtram.la -L/home/???/dynet/build/dynet/ -ldynet -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_program_options -lboost_serialization -lboost_iostreams -fopenmp
libtool: link: g++ -I/usr/include -I/home/???/eigen -I/home/???/dynet -fopenmp -I./.. -g -O2 -std=c++0x -o .libs/lamtram-train lamtram-train-main.o -fopenmp  ./.libs/liblamtram.so -L/home/???/dynet/build/dynet/ -ldynet -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_program_options -lboost_serialization -lboost_iostreams -fopenmp
/usr/bin/ld: cannot find -ldynet
